services:
  api:
    build: .
    container_name: crypta_api
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=db
      - DB_USER=admin_crypta
      - DB_PASS=Jxx871kr59@
      - DB_NAME=crypta
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: db_crypta
    environment:
      POSTGRES_USER: admin_crypta
      POSTGRES_PASSWORD: Jxx871kr59@
      POSTGRES_DB: crypta
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  pgdata:
